#!/bin/bash

function replaceline {
    echo "============================ replace(or add) $3 in $1"
    if grep -qF "$2" $1;then
        echo "pattern [$2] found and replaced by [$3]"
        sed -i "/${2}/c $3" $1
    else
        echo "pattern [$2] not found. [$3] added"
        echo "$3" >> $1
    fi
}

function addline {
    echo "============================ add $2 in $1"
    echo $2 >> $1
}

function removeline {
    echo "============================ remove lines with $2 in $1"
    fgrep -v $2 $1 > $1.tmp
    mv $1.tmp $1
}

apt-get install auditd audispd-plugins

chmod 0640 /etc/audit/audit.rules
chown root /etc/audit/audit.rules
chgrp root /etc/audit/audit.rules
chmod go-w /etc/audit/audit.rules

chmod 0640 /etc/audit/auditd.conf
chown root /etc/audit/auditd.conf
chgrp root /etc/audit/auditd.conf
chmod go-w /etc/audit/auditd.conf

addline /etc/audit/audit.rules "-w /var/www/html -p waxr"
addline /etc/audit/audit.rules "-w /etc/sudoers"

replaceline /etc/audit/auditd.conf "action_mail_acct " "action_mail_acct = root"
