#!/bin/bash

function replaceline {
    echo "============================ replace(or add) $3 in $1"
    if grep -qF "$2" $1;then
        echo "pattern [$2] found and replaced by [$3]"
        sed -i "/${2}/c $3" $1
    else
        echo "pattern [$2] not found. [$3] added"
        echo "$3" >> $1
    fi
}

function addline {
    echo "============================ add $2 in $1"
    echo $2 >> $1
}

function removeline {
    echo "============================ remove lines with $2 in $1"
    fgrep -v $2 $1 > $1.tmp
    mv $1.tmp $1
}

addline /etc/apt/apt.conf.d/50unattended-upgrades 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
addline /etc/init/control-alt-delete.override "exec /usr/bin/logger -p security.info \"Ctrl-Alt-Delete pressed\""
addline /etc/modprobe.d/somewhere "install freevxfs /bin/true"
/sbin/iptables -A FORWARD -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s -j ACCEPT
addline /etc/security/limits.conf "* hard acore 0"
addline /etc/security/limits.conf "* hard maxlogins 10"
replaceline /etc/default/irqbalance "ENABLED=" "ENABLED=0"

apt-get install selinux
addline /etc/init.d/avahi-daemon.override "manual"
replaceline /etc/selinux/config "SELINUX=" "SELINUX=enforcing"

read -p "check for nullok"
read -p "change everything to required"
nano /etc/pam.d/common-auth
nano /etc/pam.d/common-password
nano /etc/pam.d/login
 
replaceline /etc/pam.d/common-password "dcredit=" "dcredit=-1"
replaceline /etc/pam.d/common-password "ucredit=" "ucredit=-1"
replaceline /etc/pam.d/common-password "lcredit=" "lcredit=-1"
replaceline /etc/pam.d/common-password "ocredit=" "ocredit=-1"
replaceline /etc/pam.d/common-password "minlen" "minlen=8"
addline /etc/pam.d/common-password "minlen" "minlen=5"
addline /etc/pam.d/common-password "minlen" "minlen=7"
addline /etc/pam.d/common-password "minlen" "minlen=10"
addline /etc/pam.d/common-password "minlen" "minlen=9"
replaceline /etc/pam.d/common-password "retry=" "retry=3"
replaceline /etc/pam.d/common-password "difok=" "difok=3"
replaceline /etc/pam.d/common-password "reject_username minclass=" "reject_username minclass=3"

addline /etc/hosts.deny "ALL : ALL"
nano /etc/hosts.deny

rm –f /etc/sudoers.d/generic

apt-get install auditd
chown root:root /etc/shadow/
chown root:root /etc/passwd/
chown root:root /etc/profile/

touch /etc/modprobe.d/usb-storage.conf
addline /etc/modprobe.d/usb-storage.conf "install usb-storage /bin/true"

replaceline /usr/share/lightdm/lightdm.conf.d/50-guest-wrapper.conf "allow-guest" "allow-guest = false"
replaceline /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf "allow-guest" "allow-guest = false"

replaceline /etc/security/pwquality.conf "ucredit" "ucredit = -1"
replaceline /etc/modprobe.conf "install appletalk" "install appletalk /bin/true"

rm /var/log/passlong

removeline /ufw/before.rules ":ufw-http - [0:0]"
replaceline /etc/php5/cli/php.ini "open_basedir /var/www/html/"
replaceline /etc/php/cli/php.init "file_uploads" "file_uploads Off"
replaceline /etc/php5/cli/php.ini "magic_quotes_gpc" "magic_quotes_gpc Off"

replaceline /etc/host.conf "nospoof" "nospoof on"
replaceline /etc/host.conf "multi " "multi on"
replaceline /etc/host.conf "order " "order bind,hosts"
replaceline /etc/default/ufw "IPv6=" "IPv6=no"
addline /etc/ufw/before.rules "ufw-http-logdrop"

rm /etc/password

service cron start
sysv-rc-conf cron on 
sudo update-rc.d cron enable

crontab -l

nano /etc/crontab
read -p "this is /etc/spool"
ls -la /var/spool/
read -p "this is /etc/cron.d"
ls -la /etc/cron.d/
read -p "this is /etc/cron.daily"
ls -la /etc/cron.daily/
read -p "this is /etc/cron.hourly"
ls -la /etc/cron.hourly/
read -p "this is /etc/cron.monthly"
ls -la /etc/cron.monthly/
read -p "this is /etc/cron.weekly"
ls -la /etc/cron.weekly/
read -p "this is /var/spool/cron"
ls -la /var/spool/cron/
nano /etc/login.defs

replaceline /etc/login.defs "PASS_MAX_DAYS " "PASS_MAX_DAYS 30"
replaceline /etc/login.defs "PASS_MIN_DAYS " "PASS_MIN_DAYS 7"
replaceline /etc/login.defs "ENCRYPT_METHOD " "ENCRYPT_METHOD SHA512"


crontab -e
crontab -l

service cron start
sysv-rc-conf cron on 
update-rc.d cron enable

replaceline /etc/modprobe.d/modprobe.conf appletalk "install appletalk /bin/true"

echo “install squashfs /bin/true” >> /etc/modprobe.d/squashfs.conf

usermod -s /bin/false lightdm
usermod -s /bin/sync sync
usermod -s /sbin/nologin root

read -p "enable daily updates in GUI"
