#!/bin/bash

apt-get install ufw    #  install ufw
ufw enable     # enable firewall
ufw deny ftp   # blocks insecure file sharing

apt-get install gufw # instalals gufw
gufw enable # enables gufw

apt-get install  libpam-cracklib acct fail2ban clamtk auditd audispd-plugins apparmor-profiles apparmor-utils rkhunter clamav # packages to install

unalias -a

# Continous Firewall
echo "** *** sudo ufw enable" >> /etc/crontab
echo "** *** root service mysql start" >> /etc/crontab


apt-get purge telnetd -y
apt-get purge inetutils-telnetd -y 
apt-get purge telnetd-ssl -y
ufw deny 21/tcp
sudo ufw deny 21/udp
sudo apt-get --purge autoremove rsh-server -y
echo "SUBSYSTEM=="usb", ENV{UDISKS_AUTO}="0"" >> /etc/udev/rules.d/85-no-automount.rules
service udev restart
echo "manual" > /etc/init/avahi-daemon.override
echo "InitiallyPowered = false" >> /etc/bluetooth/main.conf
echo "manual" > /etc/init/cups.override
apt-get purge dovecot-* -y
echo "manual" > /etc/init/modemmanager.override
apt-get --purge autoremove sendmail -y
apt-get purge nfs-kernel-server 
apt-get purge nfs-common 
apt-get purge portmap
apt-get purge rpcbind 
apt-get purge autofs
apt-get --purge autoremove snmp
echo "install dccp /bin/true" >> /etc/modprobe.conf 
echo "install dccp_ipv4 /bin/true" >> /etc/modprobe.conf 
echo "install dccp_ipv6 /bin/true" >> /etc/modprobe.conf
echo "install rds /bin/true" >> /etc/modprobe.conf 
echo "install tipc /bin/true" >> /etc/modprobe.conf 
echo "install sctp /bin/true" >> /etc/modprobe.conf
echo "install appletalk /bin/true" >> /etc/modprobe.conf


apt-get purge putty
apt-get purge fgdump
apt-get purge ngrep
apt-get purge splunk
apt-get purge socat
apt-get purge scapy
apt-get purge sqlninja
apt-get purge sqlmap
apt-get purge hping*
apt-get purge beef
apt-get purge sslstrip
apt-get purgen expose
apt-get purge burp*
apt-get purge slueth*
apt-get purge fiddler
apt-get purge maltego

apt-get purge dig
apt-get purge tcptrace
apt-get purge openpgp
apt-get purge fport
apt-get purge ettercap
apt-get purge tcpdump
apt-get purge brutus
apt-get purge netcop
apt-get purge backtrack
apt-get purge rainbow-crack 
apt-get purge hydra-* 
apt-get purge deluge
apt-get purge john-*
apt-get purge yersinia
apt-get purge metasploit
apt-get purge wifite
apt-get purge httpry
apt-get purge nessus
apt-get purge wireshark
apt-get purge snort 
apt-get purge nikto
apt-get purge maltego
apt-get purge telnet
apt-get purge transmission
apt-get purge nmap
apt-get purge dsniff
apt-get purge aircrack-*
apt-get purge minetest 
apt-get purge nginx
apt-get purge netcat
apt-get purge bind9
apt-get purge frostwire
apt-get purge kismet
apt-get purge ophcrack # packages to purge

# ufw default
sed -i "s/^IPv6=.*/IPv6=no" >> /etc/default/ufw
ufw reload





# guest
cat /dev/null >> /etc/lightdm/lightdm.conf.d
cat /dev/null >> /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
cat /dev/null >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
echo "allow-guest=false" >> /etc/lightdm/lightdm.conf.d
echo "allow-guest=false" >> /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
echo "allow-guest=false" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
echo "greeter-show-remote-login=false" >> /etc/lightdm/lightdm.conf.d
echo "greeter-show-remote-login=false" >> /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
echo "greeter-show-remote-login=false" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
echo "greeter-show-manual-login=true" >> /etc/lightdm/lightdm.conf.d
echo "greeter-show-manual-login=true" >> /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
echo "greeter-show-manual-login=true" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf

# sshd 
sed -i "s/^PermitRootLogin.*/PermitRootLogin no/" >> /etc/ssh/sshd_config
echo "PermitRootLogin no" >> /etc/ssh/sshd_config
sed -i "s/^PassordAuthentication.*/PassordAuthentication no/" >> /etc/ssh/sshd_config
echo "PassordAuthentication no" >> /etc/ssh/sshd_config
sed -i "s/^ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/" >> etc/ssh/sshd_config
echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
sed -i "s/^PubkeyAuthentication.*/PubkeyAuthentication yes/" >> /etc/ssh/sshd_config
echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
sed -i "s/^PermitEmptyPasswords.*/PermitEmptyPasswords no/" >> /etc/ssh/sshd_config
echo "PermitEmptyPasswords no" >> /etc/ssh/sshd_config
sed -i "s/^X11Forwarding.*/X11Forwarding no/" >> /etc/ssh/sshd_config
echo "X11Forwarding no" >> /etc/ssh/sshd_config
sed -i "s/^LogLevel.*/LogLevel verbose/" >> /etc/ssh/sshd_config
echo "LogLevel VERBOSE" >> /etc/ssh/sshd_config 
sed -i "s/^AllowTcpFowarding.*/AllowTcpFowarding no/" >> /etc/ssh/sshd_config
echo "AllowTcpFowarding no" >> /etc/ssh/sshd_config
sed -i "s/^HostbasedAuthentication.*/HostbasedAuthentication no/" >> /etc/ssh/sshd_config
echo "HostbasedAuthentication no" >> /etc/ssh/sshd_config
sed -i "s/^IgnoreHosts.*/IgnoreHosts yes/" >> /etc/ssh/sshd_config
echo "IgnoreHosts yes" >> /etc/ssh/sshd_config
sed -i "s/^UseDNS.*/UseDNS yes/" >> /etc/ssh/sshd_config
echo "UseDNS yes" >> /etc/ssh/sshd_config
sed -i "s/^MaxAuthTries.*/MaxAuthTries 3/" >> /etc/ssh/sshd_config
echo "MaxAuthTries 3" >> /etc/ssh/sshd_config
sed -i "s/^Protocol.*/Protocol 2/" >> /etc/ssh/sshd_config
echo "Protocol 2" >> /etc/ssh/sshd_config
sed -i "s/^HostsAuthentication.*/HostsAuthentication yes/" >> /etc/ssh/sshd_config
echo "HostsAuthentication yes" >> /etc/ssh/sshd_config
sed -i "s/^ClientAliveInterval.*/ClientAliveInterval 300/" >> /etc/ssh/sshd_config
echo "ClientAliveInterval 300" >> /etc/ssh/sshd_config
sed -i "s/^ClientAliveCountMax.*/ClientAliveCountMax 0/" >> /etc/ssh/sshd_config
echo "ClientAliveCountMax 0" >> /etc/ssh/sshd_config
sed -i "s/^PrintLastLog.*/PrintLastLog yes/" >> /etc/ssh/sshd_config
echo "PrintLastLog yes" >> /etc/ssh/sshd_config
sed -i "s/^LoginGraceTime.*LoginGraceTime 300/" >> /etc/ssh/sshd_config
echo "LoginGraceTime 300/" >> /etc/ssh/sshd_config
sed -i "s/^MaxStartups.*/MaxStartups 2" >> /etc/ssh/sshd_config
echo "MaxStartups 2" >> /etc/ssh/sshd_config
sed -i "s/^UsePAM.*/UsePAM yes/" >> /etc/ssh/sshd_config
echo "UsePAM yes" >> /etc/ssh/sshd_config
sed -i "s/^Ciphers.*/Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc" >> /etc/ssh/sshd_config
echo "Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc/" >> /etc/ssh/sshd_config

# login.defs
echo "Login_retries 5" >> /etc/login.defs
echo "Umask 077" >> /etc/login.defs
echo "Encrypt_method SHA512" >> /etc/login.defs
echo "PASS_MAX_DAYS 30" >> /etc/login.defs
echo "PASS_MIN_DAYS 14" >> /etc/login.defs
echo "PASS_WARN_AGE 7" >> /etc/login.defs
echo "PASS_MIN_LEN 8" >> /etc/login.defs

# host.conf
echo "nospoof on" >> host.conf
echo "muli on" >> host.conf
echo "order bind,hosts" >> host.conf

# umask
echo "umask 077" >> /etc/profile
echo "umask 077" >> ~
echo "umask 077" >> /etc/login.defs
echo "umask 077" >> /etc/profile
echo "umask 077" >> /etc/ssh/sshd_config

# Sysctl 
echo "net.ipv4.ip_forward = 0"  >> /etc/sysctl.conf 
echo "net.ipv4.conf.all.rp_filter = 1" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.rp_filter = 1" >> /etc/sysctl.conf
echo "net.ipv4.icmp_echo_ignore_broadcasts = 1" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.accept_source_route = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.all.accept_source_route = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.accept_source_route = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.accept_source_route = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.send_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.send_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.tcp_syncookies = 1" >> /etc/sysctl.conf
echo "net.ipv4.tcp_max_syn_backlog = 2048" >> /etc/sysctl.conf
echo "net.ipv4.tcp_synack_retries = 2" >> /etc/sysctl.conf
echo "net.ipv4.tcp_syn_retries = 5" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.log_martians = 1" >> /etc/sysctl.conf
echo "net.ipv4.icmp_ignore_bogus_error_responses = 1" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.accept_redirects = 0 ">> /etc/sysctl.conf
echo "net.ipv6.conf.all.accept_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.accept_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.accept_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.icmp_echo_ignore_all = 1" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.secure_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.secure_redirects = 0" >> /etc/sysctl.conf
echo "kernel.exec-shield = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.router_solicitations = 0">> /etc/sysctl.conf
echo "net.ipv6.conf.default.accept_ra_rtr_pref = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.accept_ra_pinfo = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.accept_ra_defrtr = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.autoconf = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.dad_transmits = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.max_addresses = 1" >> /etc/sysctl.conf
echo "kernel.randomize_va_space = 1" >> /etc/sysctl.conf
echo "net.ipv4.tcp_keepalive_intvl = 10" >> /etc/sysctl.con
echo "net.ipv4.tcp_tw_reuse = 1" >> /etc/sysctl.con
echo "net.ipv4.tcp_keepalive_probes = 6" >> /etc/sysctl.conf
echo "net.ipv4.tcp_max_tw_buckets = 2000000" >> /etc/sysctl.conf
echo "net.ipv4.tcp_max_syn_backlog = 30000" >> /etc/sysctl.conf
echo "net.ipv4.tcp_fastopen = 3" >> /etc/sysctl.conf
echo "net.ipv4.udp_wmem_min = 8192" >> /etc/sysctl.conf
echo "net.ipv4.udp_rmem_min = 8192" >> /etc/sysctl.conf
echo "net.ipv4.tcp_wmem = 4096 65536 16777216" >> /etc/sysctl.conf
echo "net.ipv4.tcp_rmem = 4096 1048576 2097152" >> /etc/sysctl.conf
echo "net.core.optmem_max = 65536" >> /etc/sysctl.conf
echo "net.core.wmem_max = 16777216" >> /etc/sysctl.conf
echo "net.core.wmem_default = 1048576" >> /etc/sysctl.conf
echo "net.core.rmem_max = 16777216" >> /etc/sysctl.conf
echo "net.core.rmem_default = 1048576" >> /etc/sysctl.conf
echo "net.core.somaxconn = 1024" >> /etc/sysctl.conf
echo "net.core.netdev_budget_usecs = 5000" >> /etc/sysctl.conf
echo "net.core.netdev_budget = 50000" >> /etc/sysctl.conf
echo "net.core.netdev_max_backlog = 100000" >> /etc/sysctl.conf
echo "net.ipv4.tcp_mtu_probing = 1" >> /etc/sysctl.con
echo "net.ipv4.tcp_syncookies = 1" >> /etc/sysctl.con
echo "net.ipv4.tcp_rfc1337 = 1" >> /etc/sysctl.con
echo "net.ipv4.conf.default.rp_filter = 1" >> /etc/sysctl.con
echo "net.ipv4.conf.all.rp_filter = 1" >> /etc/sysctl.con
echo "net.ipv4.conf.all.log_martians = 1" >> /etc/sysctl.con
echo "net.ipv4.conf.all.accept_redirects = 0" >> /etc/sysctl.con
echo "net.ipv4.conf.default.accept_redirects = 0" >> /etc/sysctl.con
echo "net.ipv4.conf.all.secure_redirects = 0" >> /etc/sysctl.con
echo "net.ipv4.conf.default.secure_redirects = 0" >> /etc/sysctl.con
echo "net.ipv6.conf.all.accept_redirects = 0" >> /etc/sysctl.con
echo "net.ipv6.conf.default.accept_redirects = 0" >> /etc/sysctl.con
echo "net.ipv4.conf.all.send_redirects = 0" >> /etc/sysctl.con
echo "net.ipv4.conf.default.send_redirects = 0" >> /etc/sysctl.con
echo "net.ipv4.icmp_echo_ignore_all = 1" >> /etc/sysctl.con
echo "net.ipv4.ping_group_range = 100 100" >> /etc/sysctl.con
echo "net.ipv4.ping_group_range = 0 65535" >> /etc/sysctl.con
echo "vm.dirty_ratio = 10" >> /etc/sysctl.con
echo "Vm.dirty_background_ratio = 5" >> /etc/sysctl.con
echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.con
echo "dev.raid.speed_limit_max = 10000" >> /etc/sysctl.con
echo "dev.raid.speed_limit_min = 1000" >> /etc/sysctl.con
echo "Vm.dirty_background_ratio = 5" >> /etc/sysctl.con
echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.con
echo "dev.raid.speed_limit_max = 10000" >> /etc/sysctl.con
echo "dev.raid.speed_limit_min = 1000" >> /etc/sysctl.con
echo "vm.dirty_background_bytes = 4194304" >> /etc/sysctl.con
echo "vm.dirty_bytes = 4194304" >> /etc/sysctl.con
 
# mysql 
echo "slow_query_log = 1" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "symbolic-links = 0" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "bind-address = 127.0.0.1" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "local-infile = 0" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "port = 8038" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "default_password_lifetime = 30" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "safe-use-create = 1" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "secure-auth = 1" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "secure-file-priv = /tmp" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "ssl-ca = ca.pem" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "ssl-cert - server-cert.pem" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "ssl-key = server-key.pem" >> /etc/mysql/mysql.conf.d/mysqld.cnf
echo "ssl-mode = VERIFY_CA" >> /etc/mysql/mysql.conf.d/mysqld.cnf

sed -i "s/^sl-mode =.*/s/^sl-mode = 1/"  /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^symbolic-links =.*/symbolic-links = 0/"  /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^bind-address = .*/bind-address = 127.0.0.1/"  /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^local-infile =.*/local-infile = 0/"  /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^port = .*/port = 8083/"  /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^.*//" >> /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^.*//" >> /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^.*//" >> /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^.*//" >> /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^.*//" >> /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^.*//" >> /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^.*//" >> /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/^.*//" >> /etc/mysql/mysql.conf.d/mysqld.cnf


sed -i 's/^SecRuleEngine.*/SecRuleEngine On/' /etc/modsecurity/modsecurity.conf
sed -i 's/^SecRequestBodyInMemoryLimit.*/SecRequestBodyInMemoryLimit 1638400/' /etc/modsecurity/modsecurity.conf
sed -i 's/^SecResponseBodyAccess.*/SecResponseBodyAccess Off/' /etc/modsecurity/modsecurity.conf
sed -i 's/^TraceEnable.*/TraceEnable Off/'  /etc/apache2/apache2.conf
sed -i 's/^ServerTokens.*/ServerTokens Prod/'  /etc/apache2/conf-available/security.conf
sed -i 's/^ServerSignature.*/ServerSignature Off/'  /etc/apache2/conf-available/security.conf
sed -i 's/^MaxKeepAliveRequests.*/MaxKeepAliveRequests 100/'  /etc/apache2/conf-available/security.conf
sed -i 's/^LimitRequestBody.*/LimitRequestBody 204800/'  /etc/apache2/conf-available/security.conf
sed -i 's/^SSLProtocol.*/SSLProtocol all -SSLv2 -SSLv3/'  /etc/apache2/mods-available/ssl.conf
sed -i 's/^SSLHonorCipherOrder.*/SSLHonorCipherOrder On/'  /etc/apache2/mods-available/ssl.conf

sudo /etc/init.d/bind9 restart
sudo service bind9 reload


 
chown root /etc/resolv.conf
chgrp root /etc/resolv.conf
chmod 0644 /etc/resolv.conf
chmod 0644 /run/resolvconf/resolv.conf  
acledit /etc/resolv.conf


sudo apt-get install vsftpd

sed -i 's/^Anonymous_enable = .*/Anonymous_enable = NO/'  /etc/vsftpd.conf
sed -i 's/^write_enable=.*/write_enable=YES/'  /etc/vsftpd.conf
sed -i 's/^ssl_enable=.*/ssl_enable=YES/'  /etc/vsftpd.conf
sed -i 's/^chroot_local_user=.*/chroot_local_user=YES/'  /etc/vsftpd.conf
sed -i 's/^xferlog_std_format=.*/xferlog_std_format=NO/'  /etc/vsftpd.conf
sed -i 's/^log_ftp_protocol=.*/log_ftp_protocol=YES/'  /etc/vsftpd.conf
sed -i 's/^allow_anon_ssl=.*/allow_anon_ssl=NO/'  /etc/vsftpd.conf
sed -i 's/^force_local_data_ssl=.*/force_local_data_ssl=YES/'  /etc/vsftpd.conf
sed -i 's/^force_local_logins_ssl=.*/force_local_logins_ssl=YES /'  /etc/vsftpd.conf
sed -i 's/^.pasv_max_port=*/pasv_max_port=65535/'  /etc/vsftpd.conf
sed -i 's/^pasv_min_port=.*/pasv_min_port=64000/'  /etc/vsftpd.conf
sed -i 's/^local_umask=.*/local_umask=077/'  /etc/vsftpd.conf
sed -i 's/^anon_umask=.*/anon_umask=077/'  /etc/vsftpd.conf
sed -i 's/^chroot_list_file=.*/chroot_list_file=/etc/vsftpd.chroot_list/'  /etc/vsftpd.conf
iptables -I INPUT -p tcp --dport 64000:65535 -j ACCEPT

cat /dev/null >> /etc/shells
echo "# /etc/shells: valid login shells
/bin/sh
/bin/dash
/bin/bash
/bin/besh
/bin/rbash" >> /etc/shells

echo "
ServerTokens Prod
ServerSignature Off
TraceEnable Off
log_config_module
LimitRequestBody 204800
MaxKeepAliveRequests 100" >> /etc/apache2/apache2.conf
echo "
SecRuleEngine On
SecRequestBodyInMemoryLimit 1638400
SecResponseBodyAccess Off " >> /etc/modsecurity/modsecurity.conf
a2enmod * (enables all a2enmod, is wildcard)

iptables -A INPUT -p tcp --tcp-flags SYN,ACK SYN,ACK -m state --state NEW -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

iptables -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
iptables -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP

iptables -A INPUT -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
iptables -A INPUT -p tcp --tcp-flags ACK,FIN FIN -j DROP
iptables -A INPUT -p tcp --tcp-flags ACK,PSH PSH -j DROP
iptables -A INPUT -p tcp --tcp-flags ACK,URG URG -j DROP


# /etc/profile
sed -i "s/^umask.*/umask 077/" >> /etc/profile
 

# permissions 
chgrp root /etc/passwd
chmod 0600 /etc/passwd 
chown root /etc/passwd
chgrp root /etc/shadow
chmod 0000 /etc/shadow 
chown root /etc/shadow
chgrp root /etc/gshadow
chmod 0000 /etc/gshadow
Chown root /etc/gshadow
chown root /etc/securetty
chmod 0644 /etc/samba/smb.conf
chown root /etc/samba/smb.conf
chgrp root /etc/samba/smb.conf
chown root /var/log/auth.log
chmod 4755 /bin/su
chown root /bin/su
chgrp root /bin/su
chmod 1777 /tmp
chgrp root /tmp
chown root /tmp
chmod 644 /etc/profile
chgrp root /etc/profile
chown root:root /etc/profile

# delete mp files
find / -iname "*.mp3" > mp3.txt
for $line in mp3.txt; do
    rm $line
find / -iname "*.mp4" > mp4.txt
for $line in mp4.txt; do
    rm $line

# /etc/default/ufw
sed -i "s/^ipv6.*/ipv6=no/"  /etc/default/ufw

# /etc/issue
rm /etc/issue
touch /etc/issue

# apparmor
apt-get install apparmor-utils
chmod go-w /etc/audit/audit.rules
chgrp root /etc/audit/audit.rules
chmod 0640 /etc/audit/audit.rules
chown root /etc/audit/audit.rules
chmod go-w /etc/audit/auditd.conf
chgrp root /etc/audit/auditd.conf
chown root /etc/audit/auditd.conf
chmod 0640 /etc/audit/auditd.conf
echo "b-32 b-64
-a exit,always -S unlink -S rmdir
# monitor open() system call by Linux UID 1001.
-a exit,always -S open -F loginuid=1001
# monitor write-access and change in file properties (read/write/execute) of the following files.
-w /etc/group -p wa
-w /etc/passwd -p wa
-w /etc/shadow -p wa
-w /etc/sudoers -p wa
# monitor read-access of the following directory.
-w /etc/secret_directory -p r
# configure the system to audit execution of module management programs
-w /sbin/insmod -p x -k modules
-w /sbin/rmmod -p x -k modules
-w /sbin/modprobe -p x -k modules
-a always,exit -F arch=[ARCH] -S init_module -S delete_module -k modules
# audit changing of file ownership (chown, fchown, fchownat)
-a always,exit -F arch=[ARCH] -S chown -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S chown -F auid=0 -k perm_mod 
# audit calls to 'fchown' (file ownership)
-a always,exit -F arch=[ARCH] -S fchown -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S fchown -F auid=0 -k perm_mod 
# audit calls to 'fchownat' (file ownership)
-a always,exit -F arch=[ARCH] -S fchownat -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S fchownat -F auid=0 -k perm_mod
# audit calls to 'lchown' (file ownership)
-a always,exit -F arch=[ARCH] -S lchown -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S lchown -F auid=0 -k perm_mod
# audit changing of file permissions (chmod, fchmod, fchmodat)
-a always,exit -F arch=[ARCH] -S chmod -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S chmod -F auid=0 -k perm_mod
# audit calls to 'fchmod' (file permissions)
-a always,exit -F arch=[ARCH] -S fchmod -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S fchmod -F auid=0 -k perm_mod
# audit calls to 'fchmodat' (file permissions)
-a always,exit -F arch=[ARCH] -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S fchmodat -F auid=0 -k perm_mod
# audit DAC modifications (file permissions) via fremovexattr
-a always,exit -F arch=[ARCH] -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S fremovexattr -F auid=0 -k perm_mod
# audit DAC modifications (file permissions) via fsetxattr
-a always,exit -F arch=[ARCH] -S fsetxattr -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S fsetxattr -F auid=0 -k perm_mod
# audit DAC modifications (file permissions) via lremovexattr
-a always,exit -F arch=[ARCH] -S lremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S lremovexattr -F auid=0 -k perm_mod
# audit DAC modifications (file permissions) via lsetxattr
-a always,exit -F arch=[ARCH] -S lsetxattr -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S lsetxattr -F auid=0 -k perm_mod
# audit DAC modifications (file permissions) via removexattr
-a always,exit -F arch=[ARCH] -S removexattr -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S removexattr -F auid=0 -k perm_mod
# audit DAC modifications (file permissions) via setxattr
-a always,exit -F arch=[ARCH] -S setxattr -F auid>=500 -F auid!=4294967295 -k perm_mod 
-a always,exit -F arch=[ARCH] -S setxattr -F auid=0 -k perm_mod
# audit unsuccessful attempts to access files
-a always,exit -F arch=[ARCH] -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access 
-a always,exit -F arch=[ARCH] -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access 
-a always,exit -F arch=[ARCH] -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid=0 -k access 
-a always,exit -F arch=[ARCH] -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid=0 -k access
# audit_account_changes 
-w /etc/group -p wa -k audit_account_changes 
-w /etc/passwd -p wa -k audit_account_changes 
-w /etc/gshadow -p wa -k audit_account_changes 
-w /etc/shadow -p wa -k audit_account_changes 
-w /etc/security/opasswd -p wa -k audit_account_changes
# audit_network_modifications 
-a always,exit -F arch=[ARCH] -S sethostname -S setdomainname -k audit_network_modifications 
-w /etc/issue -p wa -k audit_network_modifications 
-w /etc/issue.net -p wa -k audit_network_modifications 
-w /etc/hosts -p wa -k audit_network_modifications 
-w /etc/sysconfig/network -p wa -k audit_network_modifications
# audit successful file system mounts
-a always,exit -F arch=[ARCH] -S mount -F auid>=500 -F auid!=4294967295 -k export
-a always,exit -F arch=[ARCH] -S mount -F auid=0 -k export
# audit user deletions of files and programs
-a always,exit -F arch=[ARCH] -S rmdir -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete
-a always,exit -F arch=[ARCH] -S rmdir -S unlink -S unlinkat -S rename -S renameat -F auid=0 -k delete
# audit changes to the /etc/sudoers file
-w /etc/sudoers -p wa -k actions
# lock the audit configuration to prevent any modification of this file.
-e 2

" >> /etc/audit/audit.rules 
