#!/bin/bash

function replaceline {
    echo "============================ replace(or add) $3 in $1"
    if grep -qF "$2" $1;then
        echo "pattern [$2] found and replaced by [$3]"
        sed -i "/${2}/c $3" $1
    else
        echo "pattern [$2] not found. [$3] added"
        echo "$3" >> $1
    fi
}

function addline {
    echo "============================ add $2 in $1"
    echo $2 >> $1
}

function removeline {
    echo "============================ remove lines with $2 in $1"
    fgrep -v $2 $1 > $1.tmp
    mv $1.tmp $1
}
apt-get -f install
apt-get install php

replaceline /etc/php/7.0/cli/php.ini "engine =" "engine = On"
replaceline /etc/php/7.0/cli/php.ini "expose_php =" "expose_php = Off"
replaceline /etc/php/7.0/cli/php.ini "error_reporting =" "error_reporting = E_All"
replaceline /etc/php/7.0/cli/php.ini "error_reporting =" "error_reporting = E_ALL"
replaceline /etc/php/7.0/cli/php.ini "display_errors =" "display_errors = Off"
replaceline /etc/php/7.0/cli/php.ini "display_startup_errors =" "display_startup_errors = Off"
replaceline /etc/php/7.0/cli/php.ini "log_errors =" "log_errors = On"
replaceline /etc/php/7.0/cli/php.ini "ignore_repeated_errors =" "ignore_repeated_errors = On"
replaceline /etc/php/7.0/cli/php.ini "allow_url_fopen =" "allow_url_fopen = Off"
replaceline /etc/php/7.0/cli/php.ini "allow_url_include =" "allow_url_include = Off"
replaceline /etc/php/7.0/cli/php.ini "variables_order =" 'variables_order = "GPCS"'
replaceline /etc/php/7.0/cli/php.ini "allow_webdav_methods =" "allow_webdav_methods = Off"
replaceline /etc/php/7.0/cli/php.ini "file_uploads =" "file_uploads = On"
replaceline /etc/php/7.0/cli/php.ini "max_file_uploads =" "max_file_uploads = 2"
replaceline /etc/php/7.0/cli/php.ini "enable_dl =" "enable_dl = Off"
replaceline /etc/php/7.0/cli/php.ini "session.auto_start =" "session.auto_start = Off"
replaceline /etc/php/7.0/cli/php.ini "session.hash_function =" "session.hash_function = 1"
replaceline /etc/php/7.0/cli/php.ini "session.hash_bits_per_character =" "session.hash_bits_per_character = 6"
replaceline /etc/php/7.0/cli/php.ini "session.use_trans_sid =" "session.use_trans_sid = 0"
replaceline /etc/php/7.0/cli/php.ini "session.cookie_lifetime =" "session.cookie_lifetime = 0"
replaceline /etc/php/7.0/cli/php.ini "session.cookie_secure =" "session.cookie_secure = On" 
replaceline /etc/php/7.0/cli/php.ini "session.cookie_httponly =" "session.cookie_httponly = 1"
replaceline /etc/php/7.0/cli/php.ini "session.use_only_cookies =" "session.use_only_cookies = 1"
replaceline /etc/php/7.0/cli/php.ini "session.cache_expire =" "session.cache_expire = 30"
replaceline /etc/php/7.0/cli/php.ini "default_socket_timeout =" "default_socket_timeout = 60"
replaceline /etc/php/7.0/cli/php.ini "memory_limit =" "memory_limit = 32M"
replaceline /etc/php/7.0/cli/php.ini "post_max_size =" "post_max_size = 32M"
replaceline /etc/php/7.0/cli/php.ini "max_execution_time =" "max_execution_time = 60"
replaceline /etc/php/7.0/cli/php.ini "report_memleaks =" "report_memleaks = On"
replaceline /etc/php/7.0/cli/php.ini "track_errors =" "track_errors = Off"
replaceline /etc/php/7.0/cli/php.ini "html_errors =" "html_errors = Off"

addline /etc/php/7.0/cli/php.ini "disable_functions = system, exec, shell_exec, passthru, phpinfo, show_source, popen, proc_open"
addline /etc/php/7.0/cli/php.ini "disable_functions = fopen_with_path, dbmopen, dbase_open, putenv, move_uploaded_file"
addline /etc/php/7.0/cli/php.ini "disable_functions = chdir, mkdir, rmdir, chmod, rename"
addline /etc/php/7.0/cli/php.ini "disable_functions = filepro, filepro_rowcount, filepro_retrieve, posix_mkfi"
